//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCVLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Jobs = new HashSet<Job>();
            this.Member_Company = new HashSet<Member_Company>();
        }
    
        public int Company_ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Verification_Code { get; set; }
        public Nullable<bool> Verification_Status { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public Nullable<System.TimeSpan> Registration_time { get; set; }
        public Nullable<int> Registration_ID { get; set; }
        public Nullable<int> Member_No { get; set; }
        public Nullable<int> Job_ID { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<Member_Company> Member_Company { get; set; }
    }
}
