//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCVLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalBackground
    {
        public int Education_ID { get; set; }
        public int Member_ID { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Education_Level { get; set; }
        public string certification { get; set; }
        public string Institution { get; set; }
        public string Grade { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
