//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCVLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hobby
    {
        public int hobby_id { get; set; }
        public Nullable<int> member_no { get; set; }
        public string hobby_name { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
