//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCVLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Company
    {
        public int Link_ID { get; set; }
        public Nullable<int> Member_No { get; set; }
        public Nullable<int> Company_ID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Member Member { get; set; }
    }
}
