//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCVLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoAlbum
    {
        public string PictureDescription { get; set; }
        public Nullable<int> member_No { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public string Album_Name { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
        public Nullable<System.TimeSpan> Upload_Time { get; set; }
        public int pictureID { get; set; }
        public string Name { get; set; }
    }
}
