//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCVLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_ID { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<System.TimeSpan> Transaction_Time { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
