//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCVLtd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int Work_ID { get; set; }
        public Nullable<int> Member_No { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Job_Title { get; set; }
        public string Job_Description { get; set; }
        public string Company { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
